### ISSUE TITLE
Working only for prs to default branch

### ISSUE THREAD

**Issue by alt-13** [nearform-actions/github-action-check-linked-issues#499]
If you create the pr with main/master (default branch) as the base the closingIssuesReferences does return the issue.
As the issue on GitHub is only closed if it is merged into the default branch, this makes sense.

Is there a way to make this workflow work also for prs where the base branch is not the default branch? (Maybe via timelineItems or pr body?)
Inspiration:
https://github.com/marketplace/actions/verify-linked-issue

**Comment by synapse** [comment]
Here's a working GH workflow for closing all linked issues in the PR body.

``` yaml
name: Close Linked Issues

on:
  pull_request:
    types: [closed]
    branches:
      - my_branch_name

jobs:

  close-linked-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Close Linked Issues
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            sort: 'updated',
            direction: 'desc',
            per_page: 100
          })
          .then(({ data: issues }) => {
            issues.forEach(async issue => {
              const issueNumber = issue.number
              const prBody = context.payload.pull_request.body.toLowerCase()
              const regex = /(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) #\d+/i
              const isLinkedIssue = regex.test(prBody)

              if (isLinkedIssue) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  state: 'closed'
                })
              }
            })
          })
```
### Usage
- generate a token with `repo` permissions and add it to the repository secrets as `GH_TOKEN`
- change the `my_branch_name` with your branch name. you can also track closed PR across multiple branches
- as per the [GH docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) the script checks for the same words to close the issue. e.g.: `close #123`

⚠ NB.: this will just retrieve the first 100 opened issues
